name = "web-fortunemusic-waiting-room"
compatibility_date = "2024-12-25"
pages_build_output_dir = "./build/client"

[env.production]
# Production environment variables
# Add your environment variables here

[env.preview]
# Preview environment variables
